test: github action

diff --git a/.github/workflows/deploy-with-fastlane.yaml b/.github/workflows/deploy-with-fastlane.yaml
--- a/.github/workflows/deploy-with-fastlane.yaml
+++ b/.github/workflows/deploy-with-fastlane.yaml
@@ -1,8 +1,11 @@
 name: Publish iOS and Android release
 
 on:
-  release:
-    types: [published]
+  push:
+    branches:
+      - main
+    # branches-ignore:
+    #   - dev
 
 env:
   FLUTTER_CHANNEL: "stable"
@@ -25,20 +28,22 @@ jobs:
         with:
           ruby-version: ${{ env.RUBY_VERSION }}
           bundler-cache: true
-          working-directory: 'ios'
+          working-directory: "ios"
 
       - name: Run Flutter tasks
         uses: subosito/flutter-action@v2.16.0
         with:
           # Remember to specify flutter version in pubspec.yaml under environment
           # https://github.com/subosito/flutter-action?tab=readme-ov-file#use-version-from-pubspecyaml
-          flutter-version-file: 'pubspec.yaml'
+          flutter-version-file: "pubspec.yaml"
           channel: ${{ env.FLUTTER_CHANNEL }}
           cache: true
 
+      # maybe.. need to build
+
       - uses: maierj/fastlane-action@v3.1.0
         with:
-          lane: 'release_app_store'
+          lane: "release_app_store"
           subdirectory: ios
           options: '{ "version_number": "${{ github.ref_name }}" }'
         env:
@@ -48,92 +53,93 @@ jobs:
           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
           MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
           APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
+          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
 
-  notify_ios:
-    name: Send Slack Notification about iOS build
-    needs: [build_ios]
-    runs-on: ubuntu-latest
-    timeout-minutes: 2
-    steps:
-      - name: Send Slack Notification about iOS build
-        uses: rtCamp/action-slack-notify@v2
-        if: ${{ !cancelled() && (success() || failure()) && env.SLACK_LOGS_WEBHOOK_PRESENT == 'true' }}
-        env:
-          SLACK_LOGS_WEBHOOK_PRESENT: ${{ secrets.SLACK_LOGS_WEBHOOK && 'true' || 'false' }}
-          SLACK_WEBHOOK: ${{ secrets.SLACK_LOGS_WEBHOOK }}
-          SLACK_CHANNEL: logs
-          SLACK_USERNAME: "${{ github.repository_owner }}"
-          SLACK_ICON: "https://github.com/${{ github.repository_owner }}.png?size=250"
-          SLACK_COLOR: "${{ contains(needs.*.result, 'success') && 'good' || 'danger' }}"
-          SLACK_TITLE: "${{ contains(needs.*.result, 'success') && 'Successfully released' || 'Error during release of' }} ${{ github.ref_name }} for iOS to TestFlight"
-          SLACK_FOOTER: "DevOps"
-          SLACK_MESSAGE: "${{ contains(needs.*.result, 'success') && 'Released:' || 'Release failed:' }} ${{github.event.head_commit.message}}"
+  # notify_ios:
+  #   name: Send Slack Notification about iOS build
+  #   needs: [build_ios]
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 2
+  #   steps:
+  #     - name: Send Slack Notification about iOS build
+  #       uses: rtCamp/action-slack-notify@v2
+  #       if: ${{ !cancelled() && (success() || failure()) && env.SLACK_LOGS_WEBHOOK_PRESENT == 'true' }}
+  #       env:
+  #         SLACK_LOGS_WEBHOOK_PRESENT: ${{ secrets.SLACK_LOGS_WEBHOOK && 'true' || 'false' }}
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_LOGS_WEBHOOK }}
+  #         SLACK_CHANNEL: logs
+  #         SLACK_USERNAME: "${{ github.repository_owner }}"
+  #         SLACK_ICON: "https://github.com/${{ github.repository_owner }}.png?size=250"
+  #         SLACK_COLOR: "${{ contains(needs.*.result, 'success') && 'good' || 'danger' }}"
+  #         SLACK_TITLE: "${{ contains(needs.*.result, 'success') && 'Successfully released' || 'Error during release of' }} ${{ github.ref_name }} for iOS to TestFlight"
+  #         SLACK_FOOTER: "DevOps"
+  #         SLACK_MESSAGE: "${{ contains(needs.*.result, 'success') && 'Released:' || 'Release failed:' }} ${{github.event.head_commit.message}}"
 
-  build_android:
-    name: Build Android
-    runs-on: ubuntu-latest
-    timeout-minutes: 20
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # build_android:
+  #   name: Build Android
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 20
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: ${{ env.RUBY_VERSION }}
-          bundler-cache: true
-          working-directory: 'android'
+  #     - name: Set up Ruby
+  #       uses: ruby/setup-ruby@v1
+  #       with:
+  #         ruby-version: ${{ env.RUBY_VERSION }}
+  #         bundler-cache: true
+  #         working-directory: "android"
 
-      - name: Run Flutter tasks
-        uses: subosito/flutter-action@v2.16.0
-        with:
-          flutter-version-file: 'pubspec.yaml'
-          channel: ${{ env.FLUTTER_CHANNEL }}
-          cache: true
+  #     - name: Run Flutter tasks
+  #       uses: subosito/flutter-action@v2.16.0
+  #       with:
+  #         flutter-version-file: "pubspec.yaml"
+  #         channel: ${{ env.FLUTTER_CHANNEL }}
+  #         cache: true
 
-      - name: Create google_service_account.json
-        run: |
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > google_service_account.json
+  #     - name: Create google_service_account.json
+  #       run: |
+  #         echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > google_service_account.json
 
-      - name: Create key.jks
-        run: |
-          echo "${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/key.jks
+  #     - name: Create key.jks
+  #       run: |
+  #         echo "${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/key.jks
 
-      - name: Create key.properties
-        run: |
-          cat <<EOF > android/key.properties
-          storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
-          keyPassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
-          keyAlias=release
-          storeFile=../key.jks
-          EOF
-        env:
-          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
+  #     - name: Create key.properties
+  #       run: |
+  #         cat <<EOF > android/key.properties
+  #         storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
+  #         keyPassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
+  #         keyAlias=release
+  #         storeFile=../key.jks
+  #         EOF
+  #       env:
+  #         ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
 
-      - uses: maierj/fastlane-action@v3.1.0
-        with:
-          lane: 'release_play_store'
-          subdirectory: android
-          options: '{ "version_number": "${{ github.ref_name }}" }'
-        env:
-          APP_PACKAGE_NAME: ${{ secrets.APP_PACKAGE_NAME }}
+  #     - uses: maierj/fastlane-action@v3.1.0
+  #       with:
+  #         lane: "release_play_store"
+  #         subdirectory: android
+  #         options: '{ "version_number": "${{ github.ref_name }}" }'
+  #       env:
+  #         APP_PACKAGE_NAME: ${{ secrets.APP_PACKAGE_NAME }}
 
-  notify_android:
-    name: Send Slack Notification about Android build
-    needs: [build_android]
-    runs-on: ubuntu-latest
-    timeout-minutes: 2
-    steps:
-      - name: Send Slack Notification about Android build
-        uses: rtCamp/action-slack-notify@v2
-        if: ${{ !cancelled() && (success() || failure()) && env.SLACK_LOGS_WEBHOOK_PRESENT == 'true' }}
-        env:
-          SLACK_LOGS_WEBHOOK_PRESENT: ${{ secrets.SLACK_LOGS_WEBHOOK && 'true' || 'false' }}
-          SLACK_WEBHOOK: ${{ secrets.SLACK_LOGS_WEBHOOK }}
-          SLACK_CHANNEL: logs
-          SLACK_USERNAME: "${{ github.repository_owner }}"
-          SLACK_ICON: "https://github.com/${{ github.repository_owner }}.png?size=250"
-          SLACK_COLOR: "${{ contains(needs.*.result, 'success') && 'good' || 'danger' }}"
-          SLACK_TITLE: "${{ contains(needs.*.result, 'success') && 'Successfully released' || 'Error during release of' }} ${{ github.ref_name }} for Android to Play Store"
-          SLACK_FOOTER: "DevOps"
-          SLACK_MESSAGE: "${{ contains(needs.*.result, 'success') && 'Released:' || 'Release failed:' }} ${{github.event.head_commit.message}}"
+  # notify_android:
+  #   name: Send Slack Notification about Android build
+  #   needs: [build_android]
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 2
+  #   steps:
+  #     - name: Send Slack Notification about Android build
+  #       uses: rtCamp/action-slack-notify@v2
+  #       if: ${{ !cancelled() && (success() || failure()) && env.SLACK_LOGS_WEBHOOK_PRESENT == 'true' }}
+  #       env:
+  #         SLACK_LOGS_WEBHOOK_PRESENT: ${{ secrets.SLACK_LOGS_WEBHOOK && 'true' || 'false' }}
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_LOGS_WEBHOOK }}
+  #         SLACK_CHANNEL: logs
+  #         SLACK_USERNAME: "${{ github.repository_owner }}"
+  #         SLACK_ICON: "https://github.com/${{ github.repository_owner }}.png?size=250"
+  #         SLACK_COLOR: "${{ contains(needs.*.result, 'success') && 'good' || 'danger' }}"
+  #         SLACK_TITLE: "${{ contains(needs.*.result, 'success') && 'Successfully released' || 'Error during release of' }} ${{ github.ref_name }} for Android to Play Store"
+  #         SLACK_FOOTER: "DevOps"
+  #         SLACK_MESSAGE: "${{ contains(needs.*.result, 'success') && 'Released:' || 'Release failed:' }} ${{github.event.head_commit.message}}"
